version: '3.8'
services:
  licensing-service:
    build:
      context: .
      target: run
    ports:
      - "8000:8000"
      - "8080:8080"
    environment:
      - MYSQL_URL=jdbc:mysql://mysqlserver/ostock
    volumes:
      - ./:/app
    depends_on:
      - mysqlserver

  mysqlserver:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=ostock
      - MYSQL_PASSWORD=ostock
      - MYSQL_DATABASE=ostock
    volumes:
      - mysql_data:/var/lib/mysql
      - mysql_config:/etc/mysql/conf.d
volumes:
  mysql_data:
  mysql_config: